### ISSUE TITLE
Add YAML list styling

### ISSUE THREAD

**Issue by 23maverick23** [23maverick23/sublime-jekyll#1]
YAML front matter styling for multi-value lists. This should support dashed newline lists, bracket inline lists, and space separated strings.

``` yaml
categories:
- foo
- bat
- bar
tags: [foo, bat, bar]
tags: foo bat bar
```
