### ISSUE TITLE
Add multi-level dictionary support to front-matter extras

### ISSUE THREAD

**Issue by 23maverick23** [23maverick23/sublime-jekyll#23]
This is for tracking the enhancement suggested by @atomi in issue #22 .

This will allow for a truly custom front-matter experience.

_Jekyll.sublime-settings_

``` json
"default_post_extras": { 
    "description": "default-description",  
    "image": {
        "feature": "imagename.jpg", 
        "credit": "author"
        }
}
```

_Jekyll front-matter output_

``` yaml

---
layout: post
title: here is a title
published: True
image:
    credit: author
    feature: imagename.jpg
description: default-description

---
```
