### ISSUE TITLE
jekyll_markdown_extension setting not working in user settings

### ISSUE THREAD

**Issue by thespacedoctor** [23maverick23/sublime-jekyll#90]
### Summary of issue

The "jekyll_markdown_extension" setting works when I set it within the project settings file but not when I set it in the User settings file. If I set `"jekyll_markdown_extension": "md"` in the project settings the extension for new posts/drafts becomes `md`, but if I move this setting into the User settings the default `markdown` extension is used instead.

### System details

- System Platform?

macOS 11

- Sublime Version?

3 - dev build 3167

**Comment by 23maverick23** [comment]
@thespacedoctor Thanks for using the package.

I am not able to reproduce your issue, so I might need some additional details from you.

1) Can you confirm that you are **completely removing** the `"jekyll_markdown_extension"` key from your project settings file (and not just passing an empty string like `""`)?
2) What do your `User` and `Project` settings files look like? Can you paste the relevant pieces here?
3) Can you confirm that you don't see any errors in your ST3 console (<kbd>control</kbd>+<kbd>`</kbd> on OSX)?

**Comment by thespacedoctor** [comment]
> Can you confirm that you are completely removing the "jekyll_markdown_extension" key from your project settings file (and not just passing an empty string like "")?

Yes, the setting is completely removed from project settings.

> What do your User and Project settings files look like? Can you paste the relevant pieces here?

User Settings:

```yaml
    // Optionally override the file extension format for Markdown files. Valid options
    // include: markdown, mdown, mkdn, mkd, md. Do not include the dot in your string value.
    // NOTE: We use "markdown" as the standard file extension for Markdown files
    // as suggested by John Gruber, developer of Markdown, in his blog post here:
    // http://daringfireball.net/linked/2014/01/08/markdown-extension
    "jekyll_markdown_extension": "md",
```

and project settings:

```yaml
    "settings":
    {
        "Jekyll":
        {
            "jekyll_posts_path": "/Users/Dave/git_repos/thespacedoctor.co.uk/_posts",
            "jekyll_drafts_path": "/Users/Dave/git_repos/thespacedoctor.co.uk/_drafts",
            "jekyll_uploads_path": "/Users/Dave/git_repos/thespacedoctor.co.uk/assests/uploads"
        }
    },
    "build_systems":
    ...
```

> Can you confirm that you don't see any errors in your ST3 console (control+` on OSX)?

yes, no errors. I'm sure the issue is something incredibly simple on my end.
